global:
  scrape_interval: 10s
scrape_configs:
 - job_name: triton
   static_configs:
    - targets:
       - triton:8002
 - job_name: envoy
   metrics_path: /stats/prometheus
   static_configs:
    - targets:
       - envoy:9901