{
 "title": "SuperSONIC Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; background: transparent !important;\">\n  <img src=\"https://github.com/fastmachinelearning/SuperSONIC/blob/main/docs/img/SuperSONIC_small_light_256.png?raw=true\" \n       alt=\"SONIC Logo\" style=\"width: 100px; margin-right: 15px; display: inline-block;\">\n  <div style=\"display: inline-block;\">\n    <h1 style=\"margin: 0; padding: 0;\">SuperSONIC Dashboard</h1>\n   <div style=\"margin: 5px 0;\">\n      <a href=\"https://fastmachinelearning.org/SuperSONIC\" target=\"_blank\" \n         style=\"margin-right: 15px; text-decoration: none;\">\n        <i class=\"fa fa-book\"></i> Documentation\n      </a>\n      <a href=\"https://github.com/fastmachinelearning/SuperSONIC/issues\" target=\"_blank\" \n         style=\"margin-right: 15px; text-decoration: none;\">\n        <i class=\"fa fa-github\"></i> GitHub Issues\n      </a>\n   </div>\n  </div>\n</div>"
   }
  },
  {
   "title": "Latency Breakdown",
   "type": "timeseries",
   "description": "Latency components measured by Triton servers, as well as total latency measured at proxy.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_compute_infer_duration_us{}[30s])) / sum ((rate(nv_inference_exec_count{}[30s]) * 1000))",
     "legendFormat": "Inference"
    },
    {
     "expr": "sum (rate(nv_inference_queue_duration_us{}[30s])) / sum ((rate(nv_inference_exec_count{}[30s]) * 1000))",
     "legendFormat": "Queue"
    },
    {
     "expr": "sum (rate(nv_inference_compute_input_duration_us{}[30s])) / sum ((rate(nv_inference_exec_count{}[30s]) * 1000))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum (rate(nv_inference_compute_output_duration_us{}[30s])) / sum ((rate(nv_inference_exec_count{}[30s]) * 1000))",
     "legendFormat": "Output"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_sum{envoy_http_conn_manager_prefix=\"ingress_grpc\"}[30s])) / sum(rate(envoy_http_downstream_rq_time_count{envoy_http_conn_manager_prefix=\"ingress_grpc\"}[30s]))",
     "legendFormat": "Total (measured at proxy)"
    }
   ]
  },
  {
   "title": "Inferences per second by model",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_count{}[30s])) by(model)",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "Inferences per second (all models)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_count{}[30s])) by(release)",
     "legendFormat": "All models"
    }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "nv_gpu_utilization{}", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "GPU power usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(nv_gpu_power_usage{} / nv_gpu_power_limit{})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes{}/nv_gpu_memory_total_bytes{}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}